import Head from 'next/head'

// component import
import Header from '../components/Header/Header';
import OurPremiumHotels from './sections/OurPremiumHotels';
import HotelPackages from './sections/HotelPackages';
import Footer from '../components/Footer';

const Home = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <OurPremiumHotels />
      <HotelPackages />
      <Footer />
    </>
  )
}

export default Home;
