import Head from 'next/head'

// header import
import Header from '../components/Header/Header';
import OurPremiumHotels from './sections/OurPremiumHotels';

const Home = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <OurPremiumHotels />
    </>
  )
}

export default Home;
